const product={id:"datafono-epayco-compacto",name:"Datáfono compacto ePayco",price:Number(document.querySelector("[data-product-price]")?.dataset.productPrice||129900)};
const state={cart:[]};
const $=(selector)=>document.querySelector(selector);
const currency=new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0});
const elements={body:document.body,menuToggle:$(".menu-toggle"),navLinks:$(".nav-links"),productQuantity:$("[data-product-quantity]"),productMinus:$("[data-product-minus]"),productPlus:$("[data-product-plus]"),addToCart:$("[data-add-to-cart]"),cartItems:$("[data-cart-items]"),cartCount:$("[data-cart-count]"),cartSubtotal:$("[data-cart-subtotal]"),cartTotal:$("[data-cart-total]"),checkoutLink:$("[data-checkout-link]"),checkoutForm:$("[data-checkout-form]"),checkoutQuantity:$("[data-checkout-quantity]"),paymentTotal:$("[data-payment-total]"),formMessage:$("[data-form-message]")};
function injectVisuals(){
  if(!$(".stats-strip")){
    const stats=document.createElement("section");
    stats.className="stats-strip";
    stats.setAttribute("aria-label","Indicadores de confianza para comercios");
    stats.innerHTML='<div class="stats-strip-inner" data-stagger><article class="stat-item"><strong>Tarjetas</strong><span>Débito y crédito en el punto de venta</span></article><article class="stat-item"><strong>Movilidad</strong><span>Cobra en local, feria o domicilio</span></article><article class="stat-item"><strong>Seguro</strong><span>Pagos presenciales protegidos</span></article><article class="stat-item"><strong>Control</strong><span>Consulta y gestiona tus ventas</span></article></div>';
    $(".hero")?.insertAdjacentElement("afterend",stats);
  }

  const title=$("#faq-title"),heading=$(".faq .section-heading"),eyebrow=$(".faq .eyebrow");
  if(title) title.textContent="Preguntas frecuentes sobre datáfonos ePayco";
  eyebrow?.remove();
  if(heading&&!heading.querySelector("p")){
    const copy=document.createElement("p");
    copy.textContent="Resolvemos las dudas más comunes sobre cómo comprar, recibir y empezar a usar tu datáfono.";
    heading.appendChild(copy);
  }

  const style=document.createElement("style");
  style.id="terminal-forced-faq-reference";
  style.textContent=`
    :root{--color-red:#ff1523;--color-red-dark:#cc0f1c;--color-black:#171717;--color-muted:#606060;--color-border:#e4e4e2;--color-soft:#f7f7f5;--shadow-card:0 12px 28px rgba(23,23,23,.05)}
    body{background:var(--color-soft)!important}.site-header{background:rgba(247,247,245,.94)!important;border-bottom:1px solid var(--color-border)!important}.brand-logo-link{background:transparent!important;padding:0!important;box-shadow:none!important}.brand-logo{width:118px!important}.nav-cta,.btn-primary{background:var(--color-red)!important}.hero::before{height:520px!important;background:radial-gradient(circle at 78% 18%,rgba(255,225,27,.16),transparent 28%),radial-gradient(circle at 10% 8%,rgba(255,21,35,.07),transparent 24%),linear-gradient(180deg,#fff 0%,var(--color-soft) 82%)!important}.hero-visual,.showcase-media{border-color:var(--color-border)!important;background:linear-gradient(180deg,var(--color-black) 0 42px,transparent 42px),radial-gradient(circle at 74% 24%,rgba(255,225,27,.22),transparent 28%),linear-gradient(135deg,rgba(255,21,35,.08),transparent 36%),#fff!important}.hero-visual::after,.showcase-media::after{content:""!important;position:absolute!important;top:16px!important;left:18px!important;width:10px!important;height:10px!important;border-radius:999px!important;background:var(--color-red)!important;box-shadow:18px 0 0 #f59e0b,36px 0 0 #22c55e!important}.stats-strip{width:100%!important;max-width:none!important;background:var(--color-black)!important;color:#fff!important}.stats-strip::after{content:""!important;display:block!important;height:4px!important;background:linear-gradient(90deg,var(--color-red),var(--color-product-yellow))!important}.stats-strip-inner{display:grid!important;width:min(100% - 32px,var(--max-width))!important;gap:18px!important;margin-inline:auto!important;padding-block:28px!important}.stat-item{display:grid!important;gap:4px!important;min-height:76px!important;align-content:center!important;border-left:1px solid rgba(255,255,255,.16)!important;padding-left:16px!important}.stat-item strong{color:#fff!important;font-size:clamp(1.25rem,3vw,1.85rem)!important;line-height:1!important}.stat-item span{max-width:220px!important;color:#c9c9c7!important;font-size:.9rem!important;font-weight:700!important}@media (min-width:700px){.stats-strip-inner{grid-template-columns:repeat(4,minmax(0,1fr))!important}}
    body .faq.section-shell,body .faq{width:100%!important;max-width:none!important;margin:0!important;padding:86px max(56px,calc((100vw - var(--max-width))/2)) 18px!important;background:#f7f7f5!important}
    body .faq .section-heading{display:block!important;max-width:620px!important;margin:0 0 56px!important;padding:0!important;gap:0!important}
    body .faq .section-heading .eyebrow{display:none!important}
    body .faq .section-heading h2{max-width:620px!important;color:#171717!important;font-size:clamp(2.6rem,5vw,4.5rem)!important;font-weight:900!important;line-height:.98!important;letter-spacing:0!important;margin:0!important}
    body .faq .section-heading p{max-width:560px!important;margin:20px 0 0!important;color:#606060!important;font-size:1.05rem!important;line-height:1.8!important}
    body .faq-list{display:block!important;max-width:none!important;margin:0!important;gap:0!important;border-top:1px solid #e4e4e2!important;border-bottom:1px solid #e4e4e2!important;counter-reset:none!important}
    body .faq details{border:0!important;border-bottom:1px solid #e4e4e2!important;border-radius:0!important;background:transparent!important;box-shadow:none!important;counter-increment:none!important;overflow:hidden!important;padding:0!important}
    body .faq details:last-child{border-bottom:0!important}
    body .faq summary{display:flex!important;min-height:73px!important;align-items:center!important;justify-content:space-between!important;gap:24px!important;padding:0!important;color:#171717!important;font-size:1rem!important;font-weight:900!important;line-height:1.3!important;cursor:pointer!important;list-style:none!important}
    body .faq summary::-webkit-details-marker{display:none!important}
    body .faq summary::before{content:none!important;display:none!important}
    body .faq summary::after{content:"+"!important;float:none!important;display:grid!important;flex:0 0 auto!important;width:28px!important;height:28px!important;place-items:center!important;border:1px solid #e4e4e2!important;border-radius:50%!important;background:transparent!important;color:#606060!important;font-size:1.12rem!important;font-weight:900!important;line-height:1!important}
    body .faq details[open] summary{border-bottom:0!important}
    body .faq details[open] summary::after{content:"-"!important;background:transparent!important;color:#606060!important}
    body .faq p{max-width:760px!important;margin:0!important;border-top:0!important;padding:0 58px 24px 0!important;color:#606060!important;font-size:1rem!important;line-height:1.75!important}
    @media (max-width:720px){body .faq.section-shell,body .faq{padding:62px 24px 14px!important}body .faq .section-heading{margin-bottom:42px!important}body .faq .section-heading h2{font-size:clamp(2.25rem,11vw,3.25rem)!important}}
  `;
  document.head.appendChild(style);
}
function formatCurrency(value){return currency.format(value).replace(/\s?COP/," COP")}
function clamp(value){const number=Number.parseInt(value,10);return Number.isFinite(number)&&number>0?number:1}
function cartItem(){return state.cart.find((item)=>item.id===product.id)}
function selectedQuantity(){return clamp(elements.productQuantity?.value)}
function setProductQuantity(value){if(elements.productQuantity)elements.productQuantity.value=clamp(value)}
function totals(){const quantity=cartItem()?.quantity||0;return{quantity,subtotal:quantity*product.price,total:quantity*product.price}}
function updatePaymentSummary(){const quantity=cartItem()?.quantity||clamp(elements.checkoutQuantity?.value);if(elements.checkoutQuantity)elements.checkoutQuantity.value=quantity;if(elements.paymentTotal)elements.paymentTotal.textContent=formatCurrency(quantity*product.price)}
function renderCart(){if(!elements.cartItems)return;const current=totals();elements.cartItems.innerHTML="";elements.cartCount.textContent=`${current.quantity} ${current.quantity===1?"producto":"productos"}`;elements.cartSubtotal.textContent=formatCurrency(current.subtotal);elements.cartTotal.textContent=formatCurrency(current.total);if(!current.quantity){const empty=document.createElement("p");empty.className="empty-cart";empty.textContent="Tu carrito está vacío. Agrega un datáfono para continuar.";elements.cartItems.appendChild(empty);updatePaymentSummary();return}const item=cartItem();const row=document.createElement("article");row.className="cart-item";row.innerHTML=`<div class="cart-item-info"><strong>${item.name}</strong><span>${formatCurrency(item.price)} x ${item.quantity}</span></div><div class="cart-actions"><div class="cart-mini-control" aria-label="Cantidad en carrito"><button type="button" data-cart-decrease aria-label="Disminuir cantidad">-</button><span>${item.quantity}</span><button type="button" data-cart-increase aria-label="Aumentar cantidad">+</button></div><button class="remove-item" type="button" data-cart-remove>Eliminar</button></div>`;elements.cartItems.appendChild(row);updatePaymentSummary()}
function addToCart(quantity=1){const item=cartItem();if(item)item.quantity+=clamp(quantity);else state.cart.push({...product,quantity:clamp(quantity)});renderCart()}
function updateCart(quantity){const item=cartItem();if(item)item.quantity=clamp(quantity);else state.cart.push({...product,quantity:clamp(quantity)});renderCart()}
function removeCart(){state.cart=[];renderCart()}
function showMessage(text,type="success"){if(!elements.formMessage)return;elements.formMessage.textContent=text;elements.formMessage.classList.remove("is-success","is-error");elements.formMessage.classList.add(type==="error"?"is-error":"is-success")}
function pulse(){if(!window.gsap||matchMedia("(prefers-reduced-motion: reduce)").matches)return;gsap.fromTo(".order-panel",{scale:.985},{scale:1,duration:.35,ease:"power2.out"})}
function setupGsapAnimations(){if(!window.gsap||matchMedia("(prefers-reduced-motion: reduce)").matches)return;const hasScroll=Boolean(window.ScrollTrigger);if(hasScroll)gsap.registerPlugin(ScrollTrigger);gsap.from(".hero-copy > *",{autoAlpha:0,y:28,duration:.75,ease:"power3.out",stagger:.08});gsap.from(".hero-visual",{autoAlpha:0,y:34,scale:.96,duration:.9,ease:"power3.out"});gsap.to(".dataphone",{y:-12,rotate:-3,duration:3,ease:"sine.inOut",repeat:-1,yoyo:true});gsap.to(".showcase-device",{y:-16,rotate:-2,duration:3.2,ease:"sine.inOut",repeat:-1,yoyo:true});gsap.to(".floating-ticket",{y:-10,duration:2.4,ease:"sine.inOut",repeat:-1,yoyo:true,stagger:.25});if(!hasScroll)return;gsap.utils.toArray("[data-animate]").forEach((element)=>gsap.from(element,{autoAlpha:0,y:30,duration:.78,ease:"power3.out",scrollTrigger:{trigger:element,start:"top 84%"}}));gsap.utils.toArray("[data-stagger]").forEach((group)=>gsap.from(group.children,{autoAlpha:0,y:24,duration:.65,ease:"power3.out",stagger:.08,scrollTrigger:{trigger:group,start:"top 84%"}}))}
elements.menuToggle?.addEventListener("click",()=>{const isOpen=elements.navLinks.classList.toggle("is-open");elements.body.classList.toggle("menu-open",isOpen);elements.menuToggle.setAttribute("aria-expanded",String(isOpen))});
elements.navLinks?.addEventListener("click",(event)=>{if(event.target.matches("a")){elements.navLinks.classList.remove("is-open");elements.body.classList.remove("menu-open");elements.menuToggle?.setAttribute("aria-expanded","false")}});
elements.productMinus?.addEventListener("click",()=>setProductQuantity(selectedQuantity()-1));elements.productPlus?.addEventListener("click",()=>setProductQuantity(selectedQuantity()+1));elements.productQuantity?.addEventListener("input",()=>setProductQuantity(selectedQuantity()));elements.addToCart?.addEventListener("click",()=>{addToCart(selectedQuantity());pulse();showMessage("Datáfono agregado. Revisa el carrito y completa tus datos para pagar.")});
elements.cartItems?.addEventListener("click",(event)=>{const item=cartItem();if(!item)return;if(event.target.matches("[data-cart-increase]"))updateCart(item.quantity+1);if(event.target.matches("[data-cart-decrease]"))item.quantity>1?updateCart(item.quantity-1):removeCart();if(event.target.matches("[data-cart-remove]"))removeCart();pulse()});
elements.checkoutLink?.addEventListener("click",(event)=>{if(!cartItem()){event.preventDefault();$("#checkout")?.scrollIntoView({behavior:"smooth",block:"start"});showMessage("Agrega al menos un datáfono al carrito para finalizar la compra.","error")}});elements.checkoutQuantity?.addEventListener("input",()=>updateCart(elements.checkoutQuantity.value));elements.checkoutForm?.addEventListener("submit",(event)=>{event.preventDefault();const quantity=cartItem()?.quantity||clamp(elements.checkoutQuantity?.value);const total=quantity*product.price;console.info("Orden lista para ePayco Checkout",{reference:`EPAYCO-DAT-${Date.now()}`,amount:total,currency:"COP",description:`${quantity} datáfono(s) ePayco`});showMessage(`Checkout preparado por ${formatCurrency(total)}. Conecta el script de ePayco para procesar el pago real.`)});
injectVisuals();renderCart();window.addEventListener("load",setupGsapAnimations);
